kind: Deployment
apiVersion: apps/v1
metadata:
  name: k8swatch
  namespace: dev-ithome
spec:
  selector:
    matchLabels:
      app: k8swatch
  replicas: 1
  template:
    metadata:
      labels:
        app: k8swatch
    spec:
      containers:
      - name: k8swatch
        image: gcr.io/xxxxx/myk8swatch:v1.0.0
        imagePullPolicy: Always


