version: '3'
services:
    httpserver:
        image: httpserver:v1.0.1
        ports:
            - "8080:8080"
        depends_on:
            - grpcserver           
        links:
        - grpcserver    
        restart: always   
        container_name: hs   
    grpcserver:
        image: grpcserver:v1.0.0
        ports:
            - 8081:8081
        restart: always
        container_name: gs

